export const GET_STATUS = "GET_STATUS";
export const GET_OCCUPANCY = "GET_OCCUPANCY";
export const GET_ROOM_SETUP = "GET_ROOM_SETUP";
export const SHOW_UNCLEAN = "SHOW_UNCLEAN";
export const SHOW_ALL = "SHOW_ALL";
export const SELECT_HALLWAY = "SELECT_HALLWAY";
export const GET_CURRENT_CALENDAR_VALUE = "GET_CURRENT_CALENDAR_VALUE";
export const LOGIN_USER = "LOGIN_USER";
